# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\x12\rcommunication\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x08Response\x12\r\n\x05reply\x18\x01 \x01(\t2O\n\rCommunication\x12>\n\x0bSendRequest\x12\x16.communication.Request\x1a\x17.communication.ResponseB\tZ\x07/protocb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007/protoc'
  _globals['_REQUEST']._serialized_start=38
  _globals['_REQUEST']._serialized_end=64
  _globals['_RESPONSE']._serialized_start=66
  _globals['_RESPONSE']._serialized_end=91
  _globals['_COMMUNICATION']._serialized_start=93
  _globals['_COMMUNICATION']._serialized_end=172
# @@protoc_insertion_point(module_scope)
